name: Run latest instalation on Ubuntu

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
   branches:
      - master

jobs:
  build-20_04:
    runs-on: ubuntu-20.04    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Ejecución de script en Bash en Ubuntu 20.04
      run: |
        chmod +x installer.sh && source installer.sh 
        source ~/.bashrc
    - name: Check installed version
      run: |
        cairo-compile --version
