name: Run latest instalation on Ubuntu

on:
  push:
    branches:
      - master

jobs:
  build-20_04:
    runs-on: ubuntu-20.04

    steps:
    - name: Ejecución de script en Bash en Ubuntu 20.04
      run: |
        ls
        chmod +x ../installer.sh && source ../installer.sh
