name: Run installer on Ubuntu

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  push:
   branches:
      - master

jobs:
  ubuntu:
    runs-on: ${{ matrix.os }}    
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, ubuntu-18.04]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run installer on Ubuntu
      run: |
        lsb_release -a
        chmod +x installer.sh && source installer.sh 
  macos:
    runs-on: ${{ matrix.os }}    
    strategy:
      matrix:
        os: [macos-12, macos-11]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run installer on Ubuntu
      run: |
        sw_vers
        chmod +x installer.sh && source installer.sh 
